Modal slider
Kevin-Solomon/starUI-component-library pull request #8
Opened 2022-01-31 12:21 UTC by Kevin-Solomon

# Modal and Slider Component

## Modal
![image](https://user-images.githubusercontent.com/80545228/151792022-1a4b2e14-bf7f-429d-a2e0-170160a674d3.png)

[Modal CodeSandBox](https://ul5t0.csb.app/pages/modal/modal.html)
 
## Slider 
![image](https://user-images.githubusercontent.com/80545228/151792093-943f3c92-8a25-4677-9287-1fa608da342d.png)

[Slider CodeSandBox](https://ul5t0.csb.app/pages/slider/slider.html)

2022-01-31 12:41 UTC, kart-c requested changes
Looks good Kevin, clean ani simple UI. I would suggest to add functionality to allow the user to close modal by clicking outside of it. A simple `clickHandler` when `modal` is active will do just fine

2022-01-31 13:07 UTC, starver20 approved these changes

2022-01-31 13:13 UTC, RahullRawat approved these changes

2022-02-01 11:55 UTC, Kevin-Solomon commented
> Looks good Kevin, clean ani simple UI. I would suggest to add functionality to allow the user to close modal by clicking outside of it. A simple `clickHandler` when `modal` is active will do just fine

I ran into bug while implimenting this feature.
Could you show me how to impliment this feature.

2022-02-01 12:00 UTC, merged